---
- hosts: "{{ target_hosts }}"
  vars_files:
    - ./vars/main.yml
  roles:
    - { role: "common", tags: ["deploy", "build"] }
    - { role: "mavenlibsextra", tags: ["test", "build"] }
  tasks:
    - name: Do build
      include: build.yml
      tags:
        - build
    - name: Do deploy
      include: deploy.yml
      tags:
        - deploy